name: "station"

on:
  push:
    # run the workflow only on changes
    # to the auth route and auth workflow
    branches:
      - "master"
    paths:
      - "app/stationapi.py"
      - "requirements.txt"
      - "stationapi.Dockerfile"
      - ".github/workflows/station.yml"
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
defaults:
  run:
    working-directory: .
    
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./
        file: ./stationapi.Dockerfile
        push: true
        #tags: ${{ steps.meta.outputs.tags }}
        tags: ghcr.io/fh-erfurt/cloudy:stationapi
        labels: ${{ steps.meta.outputs.labels }}
        
